version: '3'

services:

  # The PHP Application Service
  php_app:
    container_name: lemp_php
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/lempdemo
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "DB_HOST=mysql"
      - "REDIS_HOST=redis_cache"
    networks:
      - app-network

  # The Web Nginx Service
  nginx_server:
    container_name: lemp_nginx
    build:
      context: ./
      dockerfile: docker/local/nginx/Dockerfile
    volumes:
      - ./src:/var/www/lempdemmo
      - ./docker/local/nginx/conf.d/lempdemo.conf:/etc/nginx/conf.d/lempdemo.conf
      - ./docker/local/nginx/logs/access.log:/var/log/nginx/access.log
      - ./docker/local/nginx/logs/error.log:/var/log/nginx/error.log
    # port for running PHP in browser http://localhost:8000
    ports:
      - "8000:80"
      - "443:443"
    networks:
      - app-network

  # The MySQL Service
  mysql:
    container_name: lemp_mysql
    image: mysql:5.7
    volumes:
      - ./docker/local/mysql/dbdata:/var/lib/mysql/
      - ./docker/local/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - "MYSQL_DATABASE=lemp_mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - '3308:3306'
    networks:
      - app-network

  # The PHPMyadmin service
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: lemp_phpmyadmin
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "PMA_HOST=mysql"
    # port for running PHPMyAdmin in browser http://localhost:8080
    ports:
      - '8080:80'
    networks:
      - app-network

  # The Redis Service
  redis_cache:
    container_name: lemp_redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - "REDIS_HOST=redis_cache"
    networks:
      - app-network

  # The Redis-commander Service
  redis_commander:
    container_name: lemp_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - "REDIS_HOST=redis_cache"
    # port for running Redis Commander in browser http://localhost:8081
    ports:
      - 8081:8081
    hostname: redis-commander
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata: