version: '3'

services:

  # The PHP Application Service
  php_app:
    container_name: lemp_php
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/lempdemo
      - ./docker/local/php/php.ini:/usr/local/etc/conf.d/php.ini
      - ./docker/local/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis_cache
    depends_on:
      - mysql
      - redis_cache
    networks:
      - app-network

  # The Web Nginx Service
  nginx_server:
    container_name: lemp_nginx
    build:
      context: ./
      dockerfile: docker/local/nginx/Dockerfile
    volumes:
      - ./src:/var/www/lempdemo
      - ./docker/local/nginx/conf.d/lempdemo.conf:/etc/nginx/conf.d/lempdemo.conf
      - ./docker/local/nginx/logs:/var/log/nginx
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    # port for running PHP in browser http://localhost:8000
    ports:
      - "8000:80"
    # SSL:  - "443:443"
    depends_on:
      - php_app
    networks:
      - app-network

  # The MySQL Service
  mysql:
    container_name: lemp_mysql
    image: mysql:5.7
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - ./docker/local/mysql/init.sql:/data/application/init.sql
      - dbdata:/var/lib/mysql
      - ./docker/local/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      DB_HOST: mysql
      MYSQL_DATABASE: lemp_mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: r123456
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 3307:3306
    networks:
      - app-network

  # The PHPMyadmin service
  phpmyadmin:
    container_name: lemp_phpmyadmin
    image: 'phpmyadmin/phpmyadmin'
    environment:
      # define address/host name of the MySQL server
      PMA_HOST: mysql
      # (Optional) define user to auto login, match with MYSQL_USER
      PMA_USER: root
      # (Optional) define password to auto login,  match with MYSQL_PASSWORD
      PMA_PASSWORD: 123456
      # define port of the MySQL server
      PMA_PORT: 3306
      # when set to 1 connection to the arbitrary server will be allowed
      PMA_ARBITRARY: 1
    # port for running PHPMyAdmin in browser http://localhost:8001
    ports:
      - 8001:80
    depends_on:
      - mysql
    networks:
      - app-network

  # The Redis Service
  redis_cache:
    container_name: lemp_redis
    image: redis:latest
    ports:
      - 16379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    environment:
      REDIS_HOST: redis_cache
    networks:
      - app-network

  # The Redis-commander Service
  redis_commander:
    container_name: lemp_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis_cache
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    # port for running Redis Commander in browser http://localhost:8002
    ports:
      - 8002:8081
    hostname: redis-commander
    networks:
      - app-network
    depends_on: 
      - redis_cache

# Docker Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
  redis-data: